# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Use trusty64 base box
  config.vm.box = "ubuntu/trusty64"
  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--memory", 1536]
  end

  # Configure port forwarding
  config.vm.network "forwarded_port", guest: 80, host: 8258
  config.vm.network "forwarded_port", guest: 5000, host: 5555

  # Mount the root of the repo
  config.vm.synced_folder "../../", "/esaude"

  # DEVELOPER MODE
  # config.vm.synced_folder "/path/to/your/poc/apps/distrib/folder", "/var/www/"

  # Ensure packages are up to date
  config.vm.provision :shell do |shell|
      # Uncomment the line below if you're in the Jembi Cape Town office
      shell.inline = "echo \"Acquire::http::Proxy \\\"http://192.168.1.53:3142\\\";\" > /etc/apt/apt.conf.d/01proxy; sudo apt-get update"
      #shell.inline = "sudo apt-get update"
  end

  # Install required puppet modules
  config.vm.provision :shell do |shell|
    shell.inline = "mkdir -p /etc/puppet/modules;
      puppet module install example42/apache;"
  end

  # Apply the puppet manifest
  config.vm.provision "puppet" do |puppet|
    puppet.manifests_path = "../manifests"
    puppet.manifest_file  = "openmrs-esaude-distro.pp"
  end
end
